<?php /** @var \MediaLounge\Storyblok\Block\Container\Element $block */ ?>
<div class="block-teaser">
    <div class="content">
        <?= $block->getHeadline() ?>
    </div>
    <picture>
+        <source
+            srcset="<?= $block->transformImage($block->getImage()['filename'], '1280x460') ?>"
+            media="(min-width: 768px)"
+        >
+        <img
+            src="<?= $block->transformImage($block->getImage()['filename'], '768x768/smart') ?>"
+            alt="<?= __('New Luma Collection') ?>"
+        >
+    </picture>
+    <div class="content">
+        <?= $block->getTitle() ?>
+        <?= $block->renderWysiwyg($block->getContent()) ?>
+    </div>
</div>